function param = loadnidaqmx
%LOADNIDAQMX calls loadlibrary with the appropriate input arguments.
%
% This function will call loadlibrary if needed with the predefined protocal file.
% This file is automatically generated by the loadlibrarygui.
%
%   See also
%   LOADLIBRARY, UNLOADLIBRARY, UNLOADNIDAQMX

%
%
% $Author: $
% $Revision: $
% $Date: 27-May-2011 02:04:42 $
%
% Local Functions Defined:
%
%
% $Notes:
%
%
%
%
% $EndNotes
%
% $Description:
%
%
%
%
% $EndDescription


% If Library is loaded already unload it.

if libisloaded('nidaqmx')
	unloadnidaqmx;
end;

warningSetting1 = warning('off','MATLAB:loadlibrary:functionnotfound');
warningSetting2 = warning('off','MATLAB:loadlibrary:typenotfound');
warningSetting3 = warning('off','MATLAB:loadlibrary:enumexists');

% Load the library
switch OSBitLength
  case 32; 
    LibPath = 'C:\Windows\System32\';
    loadlibrary([LibPath,'nicaiu.dll'],@nidaqmx,'alias','nidaqmx');
  case 64;
    switch computer
      case {'PCWIN'}; % WINDOWS INSTALLED AS 32-BITS
        LibPath = 'C:\Windows\SysWOW64\';
        loadlibrary([LibPath,'nicaiu.dll'],@nidaqmx,'alias','nidaqmx');
      case {'PCWIN64'}; % WINDOWS INSTALLED AS 64-BITS
        LibPath = 'C:\Windows\System32\';
        %global BAPHYHOME
        %[R,W] = loadlibrary([LibPath,'nicaiu.dll'],['C:\Program Files (x86)\National Instruments\Shared\ExternalCompilerSupport\C\include\NIDAQmx.h'],'alias','nidaqmx','mfilename','nidaqmx64');
        loadlibrary([LibPath,'nicaiu.dll'],@nidaqmx64,'alias','nidaqmx');
      otherwise error(['Architecture ',computer,' not supported yet.'])
    end
end
%[R,W] = loadlibrary(['C:\Windows\System32\nicaiu.dll'],...
%  ['C:\Program Files (x86)\National Instruments\Shared\ExternalCompilerSupport\C\include\NIDAQmx.h'],'alias','nidaqmx');

if nargout
	%param = nidaqmx_loadConstants('C:\Program Files (x86)\National Instruments\NI-DAQ\DAQmx ANSI C Dev\include\NIDAQmx.h');
  %param.values=cat(1,param.values{:});
  %param.defines=param.names;
  param = nidaqmx_constants;
end

warning(warningSetting1);
warning(warningSetting2);
